// <auto-generated>
//     This code was auto generated by T4 template.
//     DO NOT EDIT THIS FILE MANUALLY.
// </auto-generated>

using System.Diagnostics;

namespace ArtNet.Common
{
    public static partial class ArtNetLogger
    {

        // Debug
        [DebuggerStepThrough, Conditional("ART_NET_DEVELOP_LOG")]
        public static void DevLogDebug(string message)
        {
            InternalLog(LogLevel.Debug, DefaultTag, message);
        }

        [DebuggerStepThrough, Conditional("ART_NET_DEVELOP_LOG")]
        public static void DevLogDebug(string tag, string message)
        {
            InternalLog(LogLevel.Debug, tag, message);
        }

        // Info
        [DebuggerStepThrough, Conditional("ART_NET_DEVELOP_LOG")]
        public static void DevLogInfo(string message)
        {
            InternalLog(LogLevel.Info, DefaultTag, message);
        }

        [DebuggerStepThrough, Conditional("ART_NET_DEVELOP_LOG")]
        public static void DevLogInfo(string tag, string message)
        {
            InternalLog(LogLevel.Info, tag, message);
        }

        // Warn
        [DebuggerStepThrough, Conditional("ART_NET_DEVELOP_LOG")]
        public static void DevLogWarn(string message)
        {
            InternalLog(LogLevel.Warn, DefaultTag, message);
        }

        [DebuggerStepThrough, Conditional("ART_NET_DEVELOP_LOG")]
        public static void DevLogWarn(string tag, string message)
        {
            InternalLog(LogLevel.Warn, tag, message);
        }

        // Error
        [DebuggerStepThrough, Conditional("ART_NET_DEVELOP_LOG")]
        public static void DevLogError(string message)
        {
            InternalLog(LogLevel.Error, DefaultTag, message);
        }

        [DebuggerStepThrough, Conditional("ART_NET_DEVELOP_LOG")]
        public static void DevLogError(string tag, string message)
        {
            InternalLog(LogLevel.Error, tag, message);
        }
    }
}
