name: Format check
on:
  push:

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Check formatting
        run: dotnet format whitespace Assets/ArtNet --folder -v diagnostic --verify-no-changes
